"""Tablas inicial

Revision ID: 6cff19df8e16
Revises: 
Create Date: 2016-08-14 20:11:23.810052

"""

# revision identifiers, used by Alembic.
revision = '6cff19df8e16'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciclos_nombre'), 'ciclos', ['nombre'], unique=True)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_nombre'), 'equipos', ['nombre'], unique=True)
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_nombre'), 'participantes', ['nombre'], unique=False)
    op.create_table('encuentros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_index(op.f('ix_encuentros_nombre'), 'encuentros', ['nombre'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('telefono2', sa.String(length=15), nullable=True),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('encuentro_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuentro_id'], ['encuentros.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asistencia', 'asistencias', ['participante_id', 'encuentro_id', 'equipo_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asistencia', table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_encuentros_nombre'), table_name='encuentros')
    op.drop_table('encuentros')
    op.drop_index(op.f('ix_participantes_nombre'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_index(op.f('ix_equipos_nombre'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_ciclos_nombre'), table_name='ciclos')
    op.drop_table('ciclos')
    ### end Alembic commands ###
