# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20151227_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='duracion',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set([('participante', 'encuentro', 'equipo')]),
        ),
    ]
