# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_auto_20151227_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
