# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_auto_20151227_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.Encuentro'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.Equipo'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.Participante'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='asistencia.Ciclo'),
        ),
    ]
